version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "petprod"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5454:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local